### ISSUE TITLE
Interior Flashlight E-Stop Error

### ISSUE THREAD

**Issue by LukasBaecker** [zauberzeug/field_friend#16]
We used the U4 only with smartphone-app controlling. Steering, starting and stopping the demo automation worked well but there was one issue that occurred consistently:

When triggering one of the E-Stop buttons the interior flashlight turns off and does not turn on when starting the automation again. We had to restart the robot to get the light on.

**Comment by angelom93** [comment]
Thank you @LukasBaecker for pointing this out. The problem was fixed by stopping all running automations on estop (instead of pausing it). And by insuring the same behaviour for the soft e-stop (en3) as for hardware e-stops.

**Comment by rodja** [comment]
>  The problem was fixed by stopping all running automations on estop (instead of pausing it)

I'm not sure we should stop an ongoing automation when bumper is triggered. Ideally we would try resuming the automation after a few seconds and increase the sleep times gradually.

**Comment by angelom93** [comment]
@rodja, that's correct for when the bumper is triggered. However, for the estop, we use a different approach. As it shuts down all hardware and resets their references.

**Comment by rodja** [comment]
Oh, I thought the same problem also occurs when triggering the Bumper. But for estop it is fine to stop the automation 👍
