### ISSUE TITLE
Update Reference not Working

### ISSUE THREAD

**Issue by LukasBaecker** [zauberzeug/field_friend#176]
While working with U4 we could not update the reference via the UI. We had to set the reference hardcoded in system line 192-193 otherwise the reference was overwritten by the previous one that was backed up.

**Comment by pascalzauberzeug** [comment]
Fixed by this line. The persistence wasn't saved due to the instant restart.
https://github.com/zauberzeug/field_friend/blob/81581ef9ebb9cb2b66347a69cc0cd9bab86ab34b/field_friend/localization/gnss.py#L160
