### ISSUE TITLE
[RB26] antenna_offset Parameter missing

### ISSUE THREAD

**Issue by BenGeissler** [zauberzeug/field_friend#46]
Hello, 

The parameter `antenna_offset` is missing in the [parameter.py](https://github.com/zauberzeug/field_friend/blob/main/config/ff3_config_rb26/params.py) of the rb26. I locally added the parameter by myself with the same value of the rb27 in the corresponding [parameter.py](https://github.com/zauberzeug/field_friend/blob/main/config/u3_config_rb27/params.py) so far. 

Without this fix the Webinterface of the nicegui would only load a white page and the logger would output the following:

```
rosys_1         | 2024-05-07 10:52:38.128 [ERROR] nicegui/app/app.py:118: 'antenna_offset'
rosys_1         | Traceback (most recent call last):
rosys_1         |   File "/app/nicegui/client.py", line 287, in safe_invoke
rosys_1         |     result = func(self) if len(inspect.signature(func).parameters) == 1 else func()
rosys_1         |                                                                              ^^^^^^
rosys_1         |   File "/app/main.py", line 16, in startup
rosys_1         |     system = System()
rosys_1         |              ^^^^^^^^
rosys_1         |   File "/app/field_friend/system.py", line 27, in __init__
rosys_1         |     self.field_friend = FieldFriendHardware()
rosys_1         |                         ^^^^^^^^^^^^^^^^^^^^^
rosys_1         |   File "/app/field_friend/hardware/field_friend_hardware.py", line 40, in __init__
rosys_1         |     self.ANTENNA_OFFSET: float = config_params['antenna_offset']
rosys_1         |                                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
rosys_1         | KeyError: 'antenna_offset'

**Comment by Johannes-Thiel** [comment]
While testing we discovered a bug, where the RTK point of the Robot was set to the position of the main antenna and not the centre of the Robot. This offset fixed the probelm. When adding the offset to the configs we seem to have missed the config for rb26. The offset was addet in commit [859eff2](https://github.com/zauberzeug/field_friend/commit/859eff2c18013096e47c9c11cf1186fedc0e837c) .
