### ISSUE TITLE
Problem with Keyboard Control

### ISSUE THREAD

**Issue by LukasBaecker** [zauberzeug/field_friend#7]
There is an issue with the keyboard control for driving the Fieldfriend manually. The issue occured on multiple systems and on multiple robots (U1 and U4). Driving back and turning right (Shift + Arrow Down, Shift + Arrow Right)  work as expected but left and forward is not possible. When sending multiple commands at once (e.g. letf and forward by pushing Shift + Arrow Left + Arrow Up) works. Also using the joystick or the mobile application works as expected.

**Comment by rodja** [comment]
@LukasBaecker are you using the latest Lizard firmware?

**Comment by LukasBaecker** [comment]
@rodja yes, we are using the latest version. To identify when the issue arose, we experimented by flashing older versions of Lizard and it the problem emerged with the following commit:

[remove minimum size of 4096 bytes for parse tree (#23)](https://github.com/zauberzeug/lizard/commit/055837506ef46f4f66f369b0f10b079047b163ad)

**Comment by falkoschindler** [comment]
I created https://github.com/zauberzeug/lizard/issues/29 to track this issue in the Lizard repo.

**Comment by angelom93** [comment]
The problem was solved in lizard and the fix is included in the [lizard_v0.1.9](https://github.com/zauberzeug/lizard/releases/tag/v0.1.9) release.
