### ISSUE TITLE
Robot stops, does nothing and continues after a few minutes

### ISSUE THREAD

**Issue by pascalzauberzeug** [zauberzeug/field_friend#85]
In the field U5 stopped weeding and continued after a few minutes. Restarting the robot does help.
Navigation: Straight Line
Implement: Weeding Screw

@rodja suggested that there might be a loop from which the robot can't exit, where it is not allowed to drive but doesn't detect anything either

I will try to find the log of the event.

**Comment by rodja** [comment]
This may be fixed by https://github.com/zauberzeug/field_friend/pull/102 where a list of last punch locations is managed to ensure we do not keep punching at the same location.
