### ISSUE TITLE
Mowing: not selecting new field once a mowing was already executed

### ISSUE THREAD

**Issue by LukasBaecker** [zauberzeug/field_friend#9]
I have marked out a test area using the U4 and set the corner points by recording with the robot. Then I started mowing this area which worked fine. 
Once the mowing was done I deleted the boundary of this test area and set a new one.
When starting the mowing automation on this new test area, the automation still calculated on the old field.

**Comment by LukasBaecker** [comment]
This issue might be solved with the use of the `active field` which is stored centrally in the [field_provider](https://github.com/zauberzeug/field_friend/blob/main/field_friend/automations/field_provider.py). The automation must be adapted accordingly.

**Comment by angelom93** [comment]
@LukasBaecker you were right! By using the `active field` the problem didn´t accure. I will close the PR.
